FROM apache/airflow:slim-3.0.3-python3.12
EXPOSE 8080
WORKDIR /opt/airflow

ARG INSTALL_MYSQL_CLIENT=false
ARG INSTALL_MSSQL_CLIENT=false

# Copy requirements and webserver_config
COPY ./requirements-apiserver.txt /opt/airflow/requirements.txt
COPY ./webserver_config.py /opt/airflow/webserver_config.py
COPY ./airflow.cfg /opt/airflow/airflow.cfg

# Install uv for faster package installation
RUN pip install uv

# Install Python dependencies using uv
RUN uv pip install --no-cache-dir -r /opt/airflow/requirements.txt

# RUN airflow db migrate

# Switch to non-root user
USER airflow

CMD ["airflow", "api-server"]