ITF = 100136
INTERVALO = 1
FAMCOML = 'Geral'

SOURCE_NAME = 'bcb_ptax'

ORIGINAL_COLUMNS = ['dataCotacao', 'currCode', 'cotacaoCompra', 'cotacaoVenda', 'paridadeCompra', 'paridadeVenda']
ATTRIBUTES_COLUMNS = ['DATASER', 'c3', 'a5', 'a30', 'a40', 'a41']

CURRENCY_DICT = {
    'AFN': 'Afegane - Afeganistão',
    'ETB': 'Birr - Etiópia',
    'THB': 'Baht - Tailândia',
    'PAB': 'Balboa - Panamá',
    'VES': 'Bolívar Soberano - Venezuela',
    'BOB': 'Boliviano - Bolívia',
    'GHS': 'Cedi - Gana',
    'CRC': 'Colón - Costa Rica',
    'SVC': 'Colón - El Salvador',
    'NIO': 'Córdoba - Nicarágua',
    'DKK': 'Coroa Dinamarquesa - Dinamarca',
    'ISK': 'Coroa Islandesa - Islândia',
    'NOK': 'Coroa Norueguesa - Noruega',
    'SEK': 'Coroa Sueca - Suécia',
    'CZK': 'Coroa Tcheca - República Tcheca',
    'GMD': 'Dalasi - Gâmbia',
    'DZD': 'Dinar - Argélia',
    'KWD': 'Dinar - Kuwait',
    'BHD': 'Dinar - Bahrein',
    'IQD': 'Dinar - Iraque',
    'JOD': 'Dinar - Jordânia',
    'LYD': 'Dinar - Líbia',
    'MKD': 'Denar - Macedônia',
    'RSD': 'Dinar - Sérvia',
    'SDG': 'Libra Sudanesa - Sudão',
    'TND': 'Dinar - Tunísia',
    'SSP': 'Libra Sul-Sudanesa - Sudão do Sul',
    'SDR': 'Direitos Especiais de Saque - Fundo Monetário Internacional',
    'MAD': 'Dirham - Marrocos',
    'AED': 'Dirham - Emirados Árabes Unidos',
    'STN': 'Dobra - São Tomé e Príncipe',
    'AUD': 'Dólar Australiano - Austrália',
    'BSD': 'Dólar - Bahamas',
    'BMD': 'Dólar - Bermudas',
    'CAD': 'Dólar Canadense - Canadá',
    'GYD': 'Dólar - Guiana',
    'NAD': 'Dólar - Namíbia',
    'BBD': 'Dólar - Barbados',
    'BZD': 'Dólar - Belize',
    'BND': 'Dólar - Brunei',
    'KYD': 'Dólar - Ilhas Cayman',
    'SGD': 'Dólar de Singapura - Singapura',
    'CLF': 'Unidade de Fomento - Chile',
    'FJD': 'Dólar - Fiji',
    'HKD': 'Dólar - Hong Kong',
    'TTD': 'Dólar - Trinidad e Tobago',
    'XCD': 'Dólar do Caribe Oriental - Organização dos Estados do Caribe Oriental',
    'USD': 'Dólar Americano - Estados Unidos',
    'JMD': 'Dólar - Jamaica',
    'LRD': 'Dólar - Libéria',
    'NZD': 'Dólar Neozelandês - Nova Zelândia',
    'SBD': 'Dólar - Ilhas Salomão',
    'SRD': 'Dólar - Suriname',
    'VND': 'Dong - Vietnã',
    'AMD': 'Dram - Armênia',
    'CVE': 'Escudo - Cabo Verde',
    'ANG': 'Florim - Antilhas Neerlandesas',
    'AWG': 'Florim - Aruba',
    'XCG': 'Florim - Caribe',
    'HUF': 'Florim - Hungria',
    'CDF': 'Franco Congolês - República Democrática do Congo',
    'BIF': 'Franco Burundiano - Burundi',
    'KMF': 'Franco - Comores',
    'XAF': 'Franco CFA BEAC - África Central',
    'XOF': 'Franco CFA BCEAO - África Ocidental',
    'XPF': 'Franco - Polinésia Francesa',
    'DJF': 'Franco - Djibouti',
    'GNF': 'Franco - Guiné',
    'MGA': 'Ariary - Madagascar',
    'RWF': 'Franco - Ruanda',
    'CHF': 'Franco Suíço - Suíça',
    'HTG': 'Gourde - Haiti',
    'PYG': 'Guarani - Paraguai',
    'UAH': 'Hryvnia - Ucrânia',
    'JPY': 'Iene - Japão',
    'GEL': 'Lari - Geórgia',
    'ALL': 'Lek - Albânia',
    'HNL': 'Lempira - Honduras',
    'SLL': 'Leone - Serra Leoa',
    'MDL': 'Leu - Moldávia',
    'RON': 'Leu Romeno - Romênia',
    'BGN': 'Lev Búlgaro - Bulgária',
    'GIP': 'Libra - Gibraltar',
    'EGP': 'Libra - Egito',
    'GBP': 'Libra Esterlina - Reino Unido',
    'FKP': 'Libra - Ilhas Malvinas',
    'LBP': 'Libra - Líbano',
    'SHP': 'Libra - Santa Helena',
    'SYP': 'Libra - Síria',
    'SZL': 'Lilangeni - Essuatíni',
    'LSL': 'Loti - Lesoto',
    'TMT': 'Manat - Turcomenistão',
    'MZN': 'Metical - Moçambique',
    'ERN': 'Nakfa - Eritreia',
    'NGN': 'Naira - Nigéria',
    'AOA': 'Kwanza - Angola',
    'TWD': 'Novo Dólar - Taiwan',
    'TRY': 'Lira Turca - Turquia',
    'PEN': 'Sol - Peru',
    'BTN': 'Ngultrum - Butão',
    'MRO': 'Ouguiya (antigo) - Mauritânia',
    'MRU': 'Ouguiya - Mauritânia',
    'TOP': 'Paʻanga - Tonga',
    'MOP': 'Pataca - Macau',
    'ARS': 'Peso - Argentina',
    'CLP': 'Peso - Chile',
    'COP': 'Peso - Colômbia',
    'COU': 'Unidade de Valor Real - Colômbia',
    'CUP': 'Peso - Cuba',
    'DOP': 'Peso - República Dominicana',
    'PHP': 'Peso - Filipinas',
    'MXN': 'Peso Mexicano - México',
    'UYU': 'Peso - Uruguai',
    'BWP': 'Pula - Botsuana',
    'MWK': 'Kwacha - Malaui',
    'ZMW': 'Kwacha - Zâmbia',
    'GTQ': 'Quetzal - Guatemala',
    'MMK': 'Kyat - Mianmar',
    'PGK': 'Kina - Papua-Nova Guiné',
    'LAK': 'Kip - Laos',
    'ZAR': 'Rand - África do Sul',
    'CNY': 'Yuan - China',
    'CNH': 'Yuan Offshore - China',
    'QAR': 'Rial - Catar',
    'OMR': 'Rial - Omã',
    'YER': 'Rial - Iêmen',
    'IRR': 'Rial - Irã',
    'SAR': 'Riyal - Arábia Saudita',
    'KHR': 'Riel - Camboja',
    'MYR': 'Ringgit - Malásia',
    'RUB': 'Rublo - Rússia',
    'BYN': 'Rublo Bielorrusso - Bielorrússia',
    'TJS': 'Somoni - Tajiquistão',
    'MUR': 'Rupia - Maurício',
    'NPR': 'Rupia - Nepal',
    'SCR': 'Rupia - Seychelles',
    'LKR': 'Rupia - Sri Lanka',
    'INR': 'Rupia - Índia',
    'IDR': 'Rupia - Indonésia',
    'MVR': 'Rufiyaa - Maldivas',
    'PKR': 'Rupia - Paquistão',
    'ILS': 'Shekel - Israel',
    'KGS': 'Som - Quirguistão',
    'UZS': 'Som - Uzbequistão',
    'BDT': 'Taka - Bangladesh',
    'WST': 'Tala - Samoa',
    'KZT': 'Tenge - Cazaquistão',
    'MNT': 'Tugrik - Mongólia',
    'VUV': 'Vatu - Vanuatu',
    'KRW': 'Won - Coreia do Sul',
    'TZS': 'Xelim - Tanzânia',
    'KES': 'Xelim - Quênia',
    'UGX': 'Xelim - Uganda',
    'SOS': 'Xelim - Somália',
    'PLN': 'Zloty - Polônia',
    'EUR': 'Euro - União Europeia',
    'XAU': 'Ouro - Padrão Internacional'
}
