NOME_SERIE = [
    'Índice de Atividade Econômica do Banco Central - IBC-Br',
    'Índice de Atividade Econômica do Banco Central (IBC-Br) - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Minas Gerais',
    'Índice de Atividade Econômica Regional - Minas Gerais - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Região Centro-Oeste',
    'Índice de Atividade Econômica Regional - Região Centro-Oeste - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Goiás',
    'Índice de Atividade Econômica Regional - Goiás - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Nordeste',
    'Índice de Atividade Econômica Regional - Nordeste - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Ceará',
    'Índice de Atividade Econômica Regional - Ceará - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - São Paulo',
    'Índice de Atividade Econômica Regional - Região Sudeste',
    'Índice de Atividade Econômica Regional - São Paulo - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Região Sudeste - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Rio de Janeiro',
    'Índice de Atividade Econômica Regional - Rio de Janeiro - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Espírito Santo',
    'Índice de Atividade Econômica Regional - Espírito Santo - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Região Sul',
    'Índice de Atividade Econômica Regional - Rio Grande do Sul',
    'Índice de Atividade Econômica Regional - Santa Catarina',
    'Índice de Atividade Econômica Regional - Região Sul - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Rio Grande do Sul - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Santa Catarina - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Região Norte',
    'Índice de Atividade Econômica Regional - Região Norte - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Paraná',
    'Índice de Atividade Econômica Regional - Pará',
    'Índice de Atividade Econômica Regional - Pará - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Amazonas',
    'Índice de Atividade Econômica Regional - Amazonas - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Paraná - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Bahia',
    'Índice de Atividade Econômica Regional - Bahia - com ajuste sazonal',
    'Índice de Atividade Econômica Regional - Pernambuco',
    'Índice de Atividade Econômica Regional - Pernambuco - com ajuste sazonal',
    'Índice de Confiança do Consumidor',
    'Índice de Condicoes econômicas atuais',
    'Índice de Expectativas Futuras',
    'Sondagem de Serviços - Índice de Expectativas (IE-S)',
    'Sondagem de Serviços - Índice de Expectativas (IE-S) - Dessazonalizado',
    'Sondagem de Serviços - Índice de Confiança de Serviços',
    'Sondagem de Serviços - Índice de Confiança de Serviços - Dessazonalizado',
    'Índice de Confiança do Empresário Industrial (ICEI) - Geral',
    'Índice de Confiança do Empresário Industrial (ICEI) - Condições',
    'Índice de Confiança do Empresário Industrial (ICEI) - Expectativas',
]
CODIGO_BACEN = [
    24363,
    24364,
    25379,
    25380,
    25381,
    25382,
    25383,
    25384,
    25388,
    25389,
    25390,
    25391,
    25392,
    25393,
    25394,
    25395,
    25396,
    25397,
    25398,
    25399,
    25400,
    25401,
    25402,
    25403,
    25404,
    25405,
    25406,
    25407,
    25408,
    25409,
    25410,
    25411,
    25412,
    25413,
    25415,
    25416,
    25417,
    25418,
    4393,
    4394,
    4395,
    17662,
    20341,
    17660,
    20339,
    7341,
    7342,
    7343,
]
DICT_SGS = dict(zip(CODIGO_BACEN, NOME_SERIE))

ITF = 10211
FAMCOML = 'BACEN - Índice de Atividade Econômica'
INTERVALO = 4

ORIGINAL_COLUMNS = ['data', 'valor']
ATTRIBUTES_COLUMNS = ['DATASER', 'a24']

SOURCE_NAME = 'bacen_ind_ativ_economica'
